### ISSUE TITLE
Reconsider keeping `projects-title-filter`

### ISSUE THREAD

**Issue by MobiTikula** [AbsaOSS/living-doc-generator#62]
## Question
Due to a new tool vision, there is need to be a thought, if we want to keep a feature to filter and mine just some of the projects in the filter.

**Comment by MobiTikula** [comment]
## Result of answering this question

**Current situation**
The current version of the Living Documentation Generator includes a feature that allows users to filter mining projects based on their preferences. This is used during the phase when the generator mines additional project data to update the project state for each repository issue.

This can be done by adding the wanted project name into the list of `projects-title-filter`.
```
INPUT_LIV_DOC_REPOSITORIES='[
            {
              "organization-name": "absaOSS",
              "repository-name": "living-doc-example-project",
              "query-labels": ["DocumentedFeature"],
              **"projects-title-filter": []**
            }
          ]'
```

**Questions**

1. Is this feature still relevant and does it provide necessary additional value to the generator?
2. Is there a real-life scenario where this feature is truly useful?
3. Are there any other considerations to take into account when thinking about this question?

**Answers**

1. Based on discussions with end users, the feature is **useful and relevant** for the use of the Living Documentation Generator.
2. For case, when the living documentation is intended to be generated for a single organization, but the repository is linked to projects from two organizations, such as an open-source (OSS) and a private org within the same company.
3. One point that came up and might be worth reconsidering is the method of setting the project title filter. It feels a bit odd that mining from projects is not the default behavior of the generator and that this feature needs to be explicitly enabled. It seems unusual that the user is required to configure the filter in the repository definition even in cases where they don’t want to mine additional project content. However, this approach makes sense, as it is tied to the repository configuration. In my opinion, this is a good solution overall, but it might be worth getting a second opinion on it.

Feel free to add any extra comments in this issue comment thread.

**Comment by miroslavpojer** [comment]
I agree with points 1 and 2, and I do not have anything to add.
Point 3:
The initial design goal was to provide a minimal solution - in today's context, livdoc regime activated and mining only from defined repositories. (Yeah, the valid minimum is to disable all regimes.)
- The idea of not providing an empty list with project filters is interesting. Can you make an issue for it as an enhancement?

**Comment by MobiTikula** [comment]
Closing this question issue with new enhancement issue (https://github.com/AbsaOSS/living-doc-generator/issues/74).
