### ISSUE TITLE
Reconsidering a way to activate the `projects-title-filter`

### ISSUE THREAD

**Issue by MobiTikula** [AbsaOSS/living-doc-generator#74]
## Background
This issue is based on a question issue focusing the need of keeping the `projects-title-filter` feature in the LivDoc project (https://github.com/AbsaOSS/living-doc-generator/issues/62).

"One point that came up and might be worth reconsidering is the method of setting the project title filter. It feels a bit odd that mining from projects is not the default behavior of the generator and that this feature needs to be explicitly enabled. It seems unusual that the user is required to configure the filter in the repository definition even in cases where they don’t want to mine additional project content. However, this approach makes sense, as it is tied to the repository configuration. In my opinion, this is a good solution overall, but it might be worth getting a second opinion on it."

## Feature

Consider idea of not providing an empty list with project filters.

**Comment by miroslavpojer** [comment]
We could make `projects-title-filter` optional to be defined. During the json parsing we could check if it is defined. If not we can placed empty field as default.
